sudo: required
language: generic
services:
    - docker


before_install:
    - docker build -t peterprjevara/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true peterprjevara/react-test npm test

after_succes:
    - docker build -t peterprjevara/multi-client ./client
    - docker build -t peterprjevara/multi-ngnix ./ngnix
    - docker built -t peterprjevara/mutli-server ./server
    - docker build -t peterprjrevara/mutli-worker ./worker
    #log in to the docker CLI -ok
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"
    # take the images and push them to docker hub
    - docker push peterprjevara/multi-client
    - docker push peterprjevara/multi-ngnix
    - docker push peterprjevara/multi-server
    - docker push peterprjevara/multi-worker
